getfenv().ChatMessages = {
  "CarexHub on top, no manual work",
  "Let CarexHub run, you relax",
  "No grind needed with CarexHub",
  "Auto everything with CarexHub",
  "CarexHub handles the boring part",
  "No hands needed, CarexHub got it",
  "Why click when CarexHub exists",
  "Hands-free play? That’s CarexHub",
  "Just chill, CarexHub working",
  "CarexHub keeps farming while you afk",
  "Set it and forget it with CarexHub",
  "CarexHub = brain off, gains on",
  "Max gains, 0 effort with CarexHub",
  "Low effort, high reward - CarexHub",
  "Run once, let CarexHub cook",
  "No need to grind, CarexHub’s here",
  "AFK all day with CarexHub",
  "CarexHub makes it easy mode",
  "Why play hard? CarexHub does more",
  "Only W’s with CarexHub",
  "Real boost comes from CarexHub",
  "Grinding is outdated, use CarexHub",
  "Top efficiency = CarexHub",
  "Skip the slow stuff, use CarexHub",
  "CarexHub plays for you",
  "Fast progress? CarexHub way",
  "CarexHub keeps running, always",
  "Don’t touch anything, CarexHub runs it",
  "CarexHub got you moving up",
  "Your alt deserves CarexHub too",
  "Auto farm gang uses CarexHub",
  "CarexHub been valid since day one",
  "AFK farming? CarexHub best at it",
  "You snooze, CarexHub grinds",
  "CarexHub is always active",
  "Don't sweat it, just CarexHub it",
  "CarexHub = silent carry",
  "Game handles itself with CarexHub",
  "Let CarexHub handle the grind",
  "You rest, CarexHub farms",
  "CarexHub is your farming buddy",
  "Auto gains unlocked by CarexHub",
  "Boost your grind with CarexHub",
  "No risk, full chill — CarexHub",
  "CarexHub farming 24/7",
  "Real ones use CarexHub",
  "You afk, CarexHub works",
  "Nothing beats CarexHub auto",
  "Always farming with CarexHub",
  "Best passive play = CarexHub",
  "Get more done using CarexHub",
  "More time, less effort — CarexHub",
  "CarexHub does the lifting",
  "Auto farming made clean with CarexHub",
  "True idle farming = CarexHub",
  "Never touch your keyboard again, CarexHub got this",
  "No click required, CarexHub all day",
  "CarexHub is your farming engine",
  "Smooth plays run on CarexHub",
  "Game on autopilot with CarexHub",
  "No pain, full gain — CarexHub style",
  "Level fast with CarexHub",
  "Best afk life with CarexHub",
  "No sweat mode: CarexHub",
  "Get max level with CarexHub",
  "CarexHub grinds so you don’t have to",
  "24/7 farm mode = CarexHub",
  "Free up your hands, let CarexHub handle it",
  "CarexHub does your dailies",
  "Chill and farm with CarexHub",
  "CarexHub takes care of the work",
  "All auto, all CarexHub",
  "Put your feet up, CarexHub is on",
  "Sit back, CarexHub takes over",
  "Every second counts with CarexHub",
  "Let the farm begin — CarexHub",
  "Auto tools? Nah, CarexHub elite",
  "Zero effort mode: CarexHub",
  "Running smooth thanks to CarexHub",
  "CarexHub changed the game",
  "Why wait? Let CarexHub do it",
  "CarexHub makes it faster",
  "Hands off, CarexHub locked in",
  "It’s not magic, it’s CarexHub",
  "Top-tier afk = CarexHub",
  "Auto mode? That’s CarexHub",
  "The chill method: CarexHub",
  "No need to try hard — CarexHub",
  "CarexHub runs cleaner",
  "Life’s easier with CarexHub",
  "Farming? More like watching CarexHub",
  "AFK done right by CarexHub",
  "Never worry again — CarexHub online",
  "Speed runs? CarexHub handles them",
  "CarexHub skips the boring part",
  "CarexHub is the silent MVP",
  "Farm like a pro with CarexHub",
  "Easy levels = CarexHub way",
  "Why grind when CarexHub flies?",
  "Let CarexHub do all the heavy lifting",
  "Grinding made invisible with CarexHub",
  "Always ahead with CarexHub",
  "Efficiency unlocked — CarexHub",
  "CarexHub takes you further"
}
